/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrey
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DefaultTableModel model;

    public MainFrame() {
        initComponents();
        model = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileopen = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rowcnt = new javax.swing.JTextField();
        colcnt = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Count = new javax.swing.JButton();
        Fromfile = new javax.swing.JButton();

        fileopen.setCurrentDirectory(new java.io.File("/home/andrey/Программирование/task3_java"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Backtracking");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Кол-во строк");

        jLabel2.setText("Кол-во столбцов");

        Create.setText("Создать таблицу");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Count.setText("Посчитать");
        Count.setEnabled(false);
        Count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountActionPerformed(evt);
            }
        });

        Fromfile.setText("Из файла");
        Fromfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(rowcnt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colcnt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fromfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Count)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(rowcnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colcnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create)
                    .addComponent(Count)
                    .addComponent(Fromfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        try {
            int val1 = Integer.parseInt(rowcnt.getText());
            int val2 = Integer.parseInt(colcnt.getText());
            if (val1 % 2 != 0 && val2 % 2 != 0) {
                JOptionPane.showMessageDialog(null, "Матрицу такого размера нельзя покрыть");
                Count.setEnabled(false);
                Fromfile.setEnabled(false);
            } else {
                Count.setEnabled(true);
                Fromfile.setEnabled(true);
                model.setRowCount(val1);
                model.setColumnCount(val2);
                //jTable1.setRowHeight(jTable1.getWidth()/(jTable1.getColumnCount()*2));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Некорректный ввод");
        }

    }//GEN-LAST:event_CreateActionPerformed

    private void CountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountActionPerformed
        try {
            Matrix matr = new Matrix(model);
            Domino dom = new Domino();
            int k = matr.Cover();
            if (k == -1) {
                JOptionPane.showMessageDialog(null, "Некорректные значения в таблице");
            } else {
                JOptionPane.showMessageDialog(null, Integer.toString(k));
            }

            ElementCellRenderer render = new ElementCellRenderer(matr);
            for (int i = 0; i < model.getColumnCount(); i++) {
                jTable1.getColumnModel().getColumn(i).setCellRenderer(render);
            }
            jTable1.repaint();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Некорректные значения в таблице");
        }
    }//GEN-LAST:event_CountActionPerformed

    private void FromfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromfileActionPerformed
        BufferedReader br;
        boolean result = true;
        int ret = fileopen.showDialog(null, "Открыть файл");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File f = fileopen.getSelectedFile();
            try {
                br = new BufferedReader(new InputStreamReader(new FileInputStream(f), "UTF-8"));
                String line;
                int i = 0;
                if ((line = br.readLine()) != null) {
                    String[] size = line.split(" ");
                    model.setRowCount(Integer.parseInt(size[0]));
                    model.setColumnCount(Integer.parseInt(size[1]));
                    rowcnt.setText(size[0]);
                    colcnt.setText(size[1]);
                }
                while ((line = br.readLine()) != null) {
                    String[] wrd = line.split(" ");
                    for (int j = 0; j < wrd.length; j++) {
                        model.setValueAt(wrd[j], i, j);
                    }
                    i++;
                }
                Count.setEnabled(true);
                br.close();
            } catch (UnsupportedEncodingException ex) {
                result = false;
            } catch (FileNotFoundException ex) {
                result = false;
            } catch (IOException | NumberFormatException | ArrayIndexOutOfBoundsException ex) {
                result = false;
            }
            if (!result) {
                JOptionPane.showMessageDialog(null, "Некорректный файл");
            }
        }

         /*Random rand = new Random();
         for (int i = 0;i<model.getRowCount();i++)
         for (int j = 0;j<model.getColumnCount();j++)
         model.setValueAt(Integer.toString(rand.nextInt(3)), i, j);*/
    }//GEN-LAST:event_FromfileActionPerformed

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        if (jTable1.getRowCount() != 0) {
            jTable1.setRowHeight(jTable1.getWidth() / (jTable1.getColumnCount()));        
        }
    }//GEN-LAST:event_jTable1ComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Count;
    private javax.swing.JButton Create;
    private javax.swing.JButton Fromfile;
    private javax.swing.JTextField colcnt;
    private javax.swing.JFileChooser fileopen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rowcnt;
    // End of variables declaration//GEN-END:variables
}
